<a href="https://colab.research.google.com/github/minsoo02/Python/blob/master/Python_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D%EA%B3%BC_%EC%9D%B4%EB%AF%B8%EC%A7%80_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 데이터 분석과 이미지 처리
- 데이터 분석 : 데이터를 수집하고, 분류하여 시각적으로 표현하는 과정
- 이미지 처리 : 특정한 목적에 맞게 이미지를 가공하는 과정

### 행렬의 필요성
- 컴퓨터 메모리 구조, 이미지, 표 형식 데이터는 모두 행렬로 표현 가능

### Numpy의 기본 사용법
Numpy의 차원
- 1차원 축(행) : axis 0 -> Vector
- 2차원 축(행) : axis 1 -> Matrix
- 3차원 축(행) : axis 2 -> Tensor (3차원 이상)

배열의 초기화

In [0]:
import numpy as np

list_data = [1,2,3]
array = np.array(list_data)

print(array)
print(array.size)


[1 2 3]
3


In [0]:
# 0부터 3까지 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [0]:
# 4*4 배열을 만들고, 0으로 초기화, 데이터 타입은 float
array2 = np.zeros((4,4), dtype = float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
# 3*3 배열을 만들고, 1로 초기화, 데이터 타입은 string
array3 = np.ones((3,3), dtype = str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [0]:
# 3*3배열, 0부터 9까지 랜덤하게 초기화
# 배열은 범위를 정할 때, 파라미터 값보다 1 작은 범위까지(여기서는 9까지)
array4 = np.random.randint(1, 10, (3,3))
print(array4)

[[5 3 9]
 [1 2 1]
 [5 9 7]]


In [0]:
# 평균이 0이고, 표준편차가 1, 표준정규분포를 띄는 배열
array5 = np.random.normal(0, 1, (3,3))
print(array5)

[[ 0.15979781 -1.06465229 -1.13097614]
 [-0.45890829 -0.11774574 -0.09639832]
 [ 0.3033913  -1.48622064 -0.01446499]]


배열의 합치기

In [0]:
# 가로로 합치기
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])

array8 = np.concatenate([array6, array7])

print(array8.shape)
print(array8)

(6,)
[1 2 3 4 5 6]


In [0]:
# 세로로 합치기
array11 = np.arange(4).reshape((1,4))
array12 = np.arange(8).reshape((2,4))

print(array11)
print(array12)
print('\n')

array13 = np.concatenate([array11, array12], axis=0)
print(array13)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


배열의 형태 바꾸기

In [0]:
# 1차원 배열 -> 2*2 2차원 배열
array9 = np.array([1,2,3,4])
array10 = array9.reshape((2,2))

print(array10.shape)
print(array10)

(2, 2)
[[1 2]
 [3 4]]


배열의 나누기

In [0]:
# 2*4 배열 -> 2*2배열 두 개로
array14 = np.arange(8).reshape((2,4))
left, right = np.split(array14, [2], axis=1) # array14를 나눔, index 2를 기준으로, 이 index는 열을 뜻함
print(array14)
print('\n')

print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]


[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


numpy의 상수연산

In [7]:
import numpy as np

array15 = np.random.randint(1, 10, size = 4).reshape(2,2)
print(array15)

[[1 6]
 [3 1]]


In [9]:
result_array = array15 * 2
print(result_array)

[[ 2 12]
 [ 6  2]]


서로 다른 형태의 numpy 연산(브로드캐스트)

In [19]:
array16 = np.arange(4).reshape(2,2) # 2*2
array17 = np.arange(2) # 1*2
result_array2 = array16 + array17

print(result_array2)

[[0 2]
 [2 4]]


In [23]:
array18 = np.arange(8).reshape(2,4)
array19 = np.arange(8).reshape(2,4)
result_array3 = np.concatenate([array18, array19], axis=0)

array20 = np.arange(4).reshape(4,1)

print(result_array3 + array20)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


numpy의 마스킹 연산
- 각 원소에 대하여 체크

In [26]:
array21 = np.arange(16).reshape(4,4)
print(array21)

array22 = array21 < 10
print(array22)

array21[array22] = 100
print(array21)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


numpy의 집계함수

In [30]:
array23 = np.arange(16).reshape(4,4)
print(np.max(array23))
print(np.min(array23))
print(np.sum(array23))
print(np.mean(array23))

15
0
120
7.5


In [31]:
print(array23)
print("합계: ",np.sum(array23, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]


numpy의 저장과 불러오기

In [1]:
import numpy as np

# 단일 객체 저장 및 불러오기
arr = np.arange(1,10)
np.save('saved.npy', arr)

result = np.load('saved.npy')
print(result)

[1 2 3 4 5 6 7 8 9]


In [2]:
# 복수 객체 저장 및 불러오기
arr1 = np.arange(1,10)
arr2 = np.arange(10,20)

np.savez('saved.npz', array1=arr1, array2=arr2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


numpy 원소의 정렬

In [3]:
# 오름차순 정렬
arr3 = np.array([5,6,3,2,10])
arr3.sort()

print(arr3)

[ 2  3  5  6 10]


In [4]:
# 내림차순 정렬
print(arr3[::-1])

[10  6  5  3  2]


In [7]:
# 각 열을 기준으로 정렬
arr4 = np.array([[6,5,8,9,1], [5,4,3,9,11]])
print(arr4)

arr4.sort(axis=0)
print(arr4)

[[ 6  5  8  9  1]
 [ 5  4  3  9 11]]
[[ 5  4  3  9  1]
 [ 6  5  8  9 11]]


In [9]:
# 균일한 간격으로 데이터 생성
arr5 = np.linspace(0, 10, 5) # 0부터 10까지 5개의 숫자로 채움

print(arr5)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
arr6 = np.random.randint(0, 10, (2,3))

print(arr6)

[[4 9 6]
 [3 3 7]]


In [19]:
# numpy 배열 객체 복사
arr7 = np.arange(0,10)
print('arr7',arr7)

arr8 = arr7 # numpy에서는 arr7과 arr8이 같은 주소를 바라보도록
arr8[0] = 99 
print('arr8',arr8)
print('arr7',arr7)

arr7 [0 1 2 3 4 5 6 7 8 9]
arr8 [99  1  2  3  4  5  6  7  8  9]
arr7 [99  1  2  3  4  5  6  7  8  9]


In [22]:
arr9 = np.arange(10,20)
print(arr9)

arr10 = arr9.copy() # 위와 같은 상황을 피하려면 copy()함수를 사용
arr10[0] = 99
print('arr10',arr10)
print('arr9',arr9)

[10 11 12 13 14 15 16 17 18 19]
arr10 [99 11 12 13 14 15 16 17 18 19]
arr9 [10 11 12 13 14 15 16 17 18 19]


In [24]:
# 중복된 원소를 제거
arr11 = np.array([1,1,2,2,2,3,3,4])
print(np.unique(arr11))

[1 2 3 4]
